---
title: "ggalluvium-test"
output: html_document
---

```{r setup, include=FALSE}

# http://corybrunson.github.io/ggalluvial/articles/ggalluvial.html

knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(ggalluvial)
```


```{r cars}
p <- ggplot(as.data.frame(HairEyeColor),
       aes(y = Freq,
           axis1 = Hair, axis2 = Eye, axis3 = Sex)) +
  geom_alluvium(aes(fill = Eye),
                width = 1/8, knot.pos = 0, reverse = FALSE) 



p
```


### Change Colours

```{r}
p <- p + scale_fill_manual(values = c(Brown = "#70493D", Hazel = "#E2AC76",
                               Green = "#3F752B", Blue = "#81B0E4")) 

p
```

```{r}

p <- p + guides(fill = FALSE) +
  geom_stratum(alpha = .25, width = 1/8, reverse = FALSE) 
p
```

### Add Stratum Text

```{r}
p <- p + geom_text(stat = "stratum", aes(label = after_stat(stratum)),
            reverse = FALSE) 

p
```


### Title and Change of Orientation
```{r}
p +
  scale_x_continuous(breaks = 1:3, labels = c("Hair", "Eye", "Sex")) +
  coord_flip() +
  ggtitle("Eye colors of 592 subjects, by sex and hair color")
```
