---
title: "sunburstr"
author: "Kevin O'Brien"
date: "24 November 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
library(sunburstR)
packageVersion("sunburstR")
#> [1] '2.1.6'

#Simple data should suffice for these examples.

```


```{r}
library(htmltools)
library(d3r)

dat <- data.frame(
  level1 = rep(c("a", "b"), each=3),
  level2 = paste0(rep(c("a", "b"), each=3), 1:3),
  size = c(10,5,2,3,8,6),
  stringsAsFactors = FALSE
)

```


```{r}
knitr::kable(dat)



```


### d3r

# d3r will help us build our hierarchy.

```{r}
library(d3r)
tree <- d3_nest(dat, value_cols = "size")
tree
#> {"children":[{"name":"a","children":[{"name":"a1","size":10,"colname":"level2"},{"name":"a2","size":5,"colname":"level2"},{"name":"a3","size":2,"colname":"level2"}],"colname":"level1"},{"name":"b","children":[{"name":"b1","size":3,"colname":"level2"},{"name":"b2","size":8,"colname":"level2"},{"name":"b3","size":6,"colname":"level2"}],"colname":"level1"}],"name":"root"}

```


```{r}
legend = FALSE

# Often the legend in the sunburst becomes useless with lots of nodes and multiple levels. 
# While a hack could turn it off, I don't like having to ask users to resort to hacks, so now the argument legend = FALSE will turn it off.
```


```{r}
sb1 <- sunburst(tree, width="100%", height=400)
sb2 <- sunburst(
  tree,
  legend = FALSE,
  width = "100%",
  height = 400
)

# do side-by-side for comparison
div(
  style="display: flex; align-items:center;",
  div(style="width:50%; border:1px solid #ccc;", sb1),
  div(style="width:50%; border:1px solid #ccc;", sb2)
)
```


