---
title: "``autoplot.density``Autoplot stats::density"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggfortify)
```


+,ggmultiplot,ANY-method
Generic add operator for ggmultiplot

#### Description 
 
Generic add operator for ggmultiplot

#### Usage 

<pre><code>
## S4 method for signature 'ggmultiplot,ANY'
e1 + e2
</code></pre>

#### Arguments 
 
e1 first argument
e2 second argument

Value
ggmultiplot

## apply_facets
Apply facets to to ggplot2::ggplot

#### Description 
 
Apply facets to to ggplot2::ggplot

#### Usage 
<pre><code>
apply_facets(p, formula, facets = TRUE, nrow = NULL, ncol = 1,
scales = "free_y", ...)
</code></pre>

#### Arguments 
 
* ``p`` ggplot2::ggplot instance
* ``formula`` stats::formula instance
* ``facets`` Logical value to specify use facets
* ``nrow`` Number of facet/subplot rows
* ``ncol`` Number of facet/subplot columns
* ``scales`` Scale value passed to ggplot2
* ``...`` other arguments passed to methods

Value
ggplot
apply_grid
Apply grid to to ggplot2::ggplot

#### Description 
 
Apply grid to to ggplot2::ggplot

#### Usage 
<pre><code>
apply_grid(p, formula, scales = "free_y", ...)
</code></pre>

#### Arguments 
 
* ``p`` ggplot2::ggplot instance
* ``formula`` stats::formula instance
* ``scales`` Scale value passed to ggplot2
* ``...`` other arguments passed to methods


