---
title: "ggfortify"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggfortify)
```

fortify.ts
fortify.ts
Convert time-series-like to data.frame

#### Description 
 
Convert time-series-like to data.frame

#### Usage 
 <pre><code>
## S3 method for class 'ts'
fortify(model, data = NULL, columns = NULL, is.date = NULL,
index.name = "Index", data.name = "Data", scale = FALSE, melt = FALSE,
...)

#### Arguments 
 
model time-series-like instance
data original dataset, if needed
columns character vector specifies target column name(s)
is.date logical frag indicates whether the stats::ts is date or not If not provided,
regard the input as date when the frequency is 4 or 12
index.name specify column name for time series index
data.name specify column name for univariate time series data. Ignored in multivariate
time series.
scale logical flag indicating whether to perform scaling each timeseries
melt logical flag indicating whether to melt each timeseries as variable
* ``... ``: other arguments passed to methods
Value
data.frame

#### Examples 

fortify(AirPassengers)
fortify(timeSeries::as.timeSeries(AirPassengers))
fortify(tseries::irts(cumsum(rexp(10, rate = 0.1)), matrix(rnorm(20), ncol=2)))
fortify(stats::stl(UKgas, s.window = 'periodic'))
fortify(stats::decompose(UKgas))fortify.tsmodel
fortify.tsmodel
55
Convert time series models (like AR, ARIMA) to data.frame

#### Description 
 
Convert time series models (like AR, ARIMA) to data.frame

#### Usage 
 <pre><code>
## S3 method for class 'tsmodel'
fortify(model, data = NULL, predict = NULL,
is.date = NULL, ts.connect = TRUE, ...)

#### Arguments 
 
model Time series model instance
data original dataset, needed for stats::ar, stats::Arima
predict Predicted stats::ts If not provided, try to retrieve from current environment
using variable name.
is.date Logical frag indicates whether the stats::ts is date or not. If not provided,
regard the input as date when the frequency is 4 or 12.
ts.connect Logical frag indicates whether connects original time-series and predicted val-
ues
* ``... ``: other arguments passed to methods
Value
data.frame

#### Examples 

fortify(stats::ar(AirPassengers))
fortify(stats::arima(UKgas))
fortify(stats::arima(UKgas), data = UKgas, is.date = TRUE)
fortify(forecast::auto.arima(austres))
fortify(forecast::arfima(AirPassengers))
fortify(forecast::nnetar(UKgas))
fortify(stats::HoltWinters(USAccDeaths))
data(LPP2005REC, package = 'timeSeries')
x = timeSeries::as.timeSeries(LPP2005REC)
d.Garch = fGarch::garchFit(LPP40 ~ garch(1, 1), data = 100 * x, trace = FALSE)
fortify(d.Garch)56
fortify_base
fortify.varprd
Convert vars::varprd to data.frame

#### Description 
 
Convert vars::varprd to data.frame

#### Usage 
 <pre><code>
## S3 method for class 'varprd'
fortify(model, data = NULL, is.date = NULL,
ts.connect = FALSE, melt = FALSE, ...)

#### Arguments 
 
model vars::varprd instance
data original dataset, if needed
is.date Logical frag indicates whether the stats::ts is date or not. If not provided,
regard the input as date when the frequency is 4 or 12.
ts.connect Logical frag indicates whether connects original time-series and predicted val-
ues
melt Logical flag indicating whether to melt each timeseries as variable
* ``... ``: other arguments passed to methods
Value
data.frame

#### Examples 

data(Canada, package = 'vars')
d.var <- vars::VAR(Canada, p = 3, type = 'const')
fortify(stats::predict(d.var, n.ahead = 50))
fortify_base
Convert base::table to data.frame

#### Description 
 
Convert base::table to data.frame

#### Usage 
 <pre><code>
fortify_base(model, data, ...)fortify_map
57

#### Arguments 
 
model base::table instance
data original dataset, if needed
* ``... ``: other arguments passed to methods
Value
data.frame
fortify_map
Convert maps::map to data.frame.

#### Description 
 
Convert maps::map to data.frame.

#### Usage 
 <pre><code>
fortify_map(model, data = NULL, ...)

#### Arguments 
 
model maps::map instance
data original dataset, if needed
* ``... ``: other arguments passed to methods
Value
data.frame
geom_confint
Connect observations by stairs.

#### Description 
 
Connect observations by stairs.

#### Usage 
 <pre><code>
geom_confint(mapping = NULL, data = NULL, stat = "identity",
position = "identity", na.rm = FALSE, ...)58
get.dtindex

#### Arguments 
 
* ``mapping``: the aesthetic mapping
* ``data ``: a layer specific dataset
* ``stat ``:  the statistical transformation to use on the data for this layer
position the position adjustment to use for overlapping points on this layer
na.rm logical frag whether silently remove missing values
* ``... ``: other arguments passed to methods
geom_factory
Factory function to control ggplot2::geom_xxx functions

#### Description 
 
Factory function to control ggplot2::geom_xxx functions

#### Usage 
 <pre><code>
geom_factory(geomfunc, data = NULL, ...)

#### Arguments 
 
geomfunc ggplot2::geom_xxx function
data plotting data
* ``... ``: other arguments passed to methods
Value
proto
get.dtindex
Convert ts index to Date vector

#### Description 
 
Convert ts index to Date vector

#### Usage 
 <pre><code>
get.dtindex(data, is.tsp = FALSE, is.date = NULL)get.dtindex.continuous
59

#### Arguments 
 
data ts instance
is.tsp Logical frag whether data is tsp itself or not
is.date Logical frag indicates whether the stats::ts is date or not. If not provided,
regard the input as date when the frequency is 4 or 12.
Value
vector

#### Examples 

ggfortify:::get.dtindex(AirPassengers)
ggfortify:::get.dtindex(UKgas)
ggfortify:::get.dtindex(Nile, is.date = FALSE)
ggfortify:::get.dtindex(Nile, is.date = TRUE)
get.dtindex.continuous
Get Date vector continue to ts index

#### Description 
 
Get Date vector continue to ts index

#### Usage 
 <pre><code>
get.dtindex.continuous(data, length, is.tsp = FALSE, is.date = NULL)

#### Arguments 
 
data ts instance
length A number to continue
is.tsp Logical frag whether data is tsp itself or not
is.date Logical frag indicates whether the stats::ts is date or not. If not provided,
regard the input as date when the frequency is 4 or 12.
Value
vector

#### Examples 

ggfortify:::get.dtindex.continuous(AirPassengers, length = 10)
ggfortify:::get.dtindex.continuous(UKgas, length = 10)60
get_geom_function
get.layout
Calcurate layout matrix for ggmultiplot

#### Description 
 
Calcurate layout matrix for ggmultiplot

#### Usage 
 <pre><code>
get.layout(nplots, ncol, nrow)

#### Arguments 
 
nplots Number of plots
ncol Number of grid columns
nrow Number of grid rows
Value
matrix

#### Examples 

ggfortify:::get.layout(3, 2, 2)
get_geom_function
Factory function to control ggplot2::geom_xxx functions

#### Description 
 
Factory function to control ggplot2::geom_xxx functions

#### Usage 
 <pre><code>
get_geom_function(geom, allowed = c("line", "bar", "point"))

#### Arguments 
 
geom string representation of ggplot2::geom_xxx function
allowed character vector contains allowed values
Value
functionggbiplot
61

#### Examples 

ggfortify:::get_geom_function('point')
ggfortify:::get_geom_function('line', allowed = c('line'))
ggbiplot
Draw biplot using ggplot2.

#### Description 
 
Draw biplot using ggplot2.

#### Usage 
 <pre><code>
ggbiplot(plot.data, loadings.data = NULL, colour = NULL, size = NULL,
linetype = NULL, alpha = NULL, fill = NULL, shape = NULL,
label = FALSE, label.label = "rownames", label.colour = colour,
label.alpha = NULL, label.size = NULL, label.angle = NULL,
label.family = NULL, label.fontface = NULL, label.lineheight = NULL,
label.hjust = NULL, label.vjust = NULL, label.repel = FALSE,
loadings = FALSE, loadings.colour = "#FF0000", loadings.label = FALSE,
loadings.label.label = "rownames", loadings.label.colour = "#FF0000",
loadings.label.alpha = NULL, loadings.label.size = NULL,
loadings.label.angle = NULL, loadings.label.family = NULL,
loadings.label.fontface = NULL, loadings.label.lineheight = NULL,
loadings.label.hjust = NULL, loadings.label.vjust = NULL,
loadings.label.repel = FALSE, label.show.legend = NA, frame = FALSE,
frame.type = NULL, frame.colour = colour, frame.level = 0.95,
frame.alpha = 0.2, xlim = c(NA, NA), ylim = c(NA, NA), log = "",
main = NULL, xlab = NULL, ylab = NULL, asp = NULL, ...)

#### Arguments 
 
plot.data data.frame
loadings.data data.frame
colour colour
size size
linetype line type
alpha alpha
fill fill
shape shape
label Logical value whether to display data labels
label.label Column name used for label text
label.colour Colour for text labels62
ggbiplot
label.alpha Alpha for text labels
label.size Size for text labels
label.angle Angle for text labels
label.family Font family for text labels
label.fontface Fontface for text labels
label.lineheight
Lineheight for text labels
label.hjust Horizontal adjustment for text labels
label.vjust Vertical adjustment for text labels
label.repel Logical flag indicating whether to use ggrepel, enabling this may take some
time for plotting
loadings
Logical value whether to display loadings arrows
loadings.colour
Point colour for data
loadings.label Logical value whether to display loadings labels
loadings.label.label
Column name used for loadings text labels
loadings.label.colour
Colour for loadings text labels
loadings.label.alpha
Alpha for loadings text labels
loadings.label.size
Size for loadings text labels
loadings.label.angle
Angle for loadings text labels
loadings.label.family
Font family for loadings text labels
loadings.label.fontface
Fontface for loadings text labels
loadings.label.lineheight
Lineheight for loadings text labels
loadings.label.hjust
Horizontal adjustment for loadings text labels
loadings.label.vjust
Vertical adjustment for loadings text labels
loadings.label.repel
Logical flag indicating whether to use ggrepel automatically
label.show.legend
Logical value indicating whether to show the legend of text labels
frame Logical value whether to draw outliner convex / ellipse
frame.type Character specifying frame type. ’convex’ or types supporeted by ggplot2::stat_ellipse
can be used.ggcpgram
63
frame.colour Colour for frame
frame.level Passed for ggplot2::stat_ellipse ’s level. Ignored in ’convex’.
frame.alpha Alpha for frame
xlim limits for x axis
ylim limits for y axis
log which variables to log transform ("x", "y", or "xy")
main character vector or expression for plot title
xlab character vector or expression for x axis label
ylab character vector or expression for y axis label
asp the y/x aspect ratio
* ``... ``: other arguments passed to methods
Value
ggplot
ggcpgram
Plots a cumulative periodogram

#### Description 
 
Plots a cumulative periodogram

#### Usage 
 <pre><code>
ggcpgram(ts, taper = 0.1, colour = "#000000", linetype = "solid",
conf.int = TRUE, conf.int.colour = "#0000FF",
conf.int.linetype = "dashed", conf.int.fill = NULL,
conf.int.alpha = 0.3)

#### Arguments 
 
ts stats::ts instance
taper Proportion tapered in forming the periodogram
colour Line colour
linetype Line type
conf.int
Logical flag indicating whether to plot confidence intervals
conf.int.colour
line colour for confidence intervals
conf.int.linetype
line type for confidence intervals
conf.int.fill
fill colour for confidence intervals
* ``conf.int.alpha``: alpha for confidence intervals64
ggdistribution
Value
ggplot

#### Examples 

ggcpgram(AirPassengers)
